In [1]:
import pandas as pd
import numpy as np

recs = pd.read_csv('blockbuster_recommendations.csv')

recs.head()

,Title,Genre,Languages,Series or Movie,View Rating,Popularity_Score,Netflix Link,IMDb Link,Summary,Image,Poster,Rec_1,Rec_2,Rec_3,Rec_4,Rec_5
0,Fair Game,Biography,Arabic,Movie,PG-13,0.749848,https://www.netflix.com/watch/70119704,https://www.imdb.com/title/tt0977855,"Valerie Plame finds her life, career and marri...",https://occ-0-2042-299.1.nflxso.net/dnm/api/v6...,https://images-na.ssl-images-amazon.com/images...,Argo,Heaven Without People,Lone Survivor,Wolf,Megan Leavey
1,Fair Game,Drama,Arabic,Movie,PG-13,0.749848,https://www.netflix.com/watch/70119704,https://www.imdb.com/title/tt0977855,"Valerie Plame finds her life, career and marri...",https://occ-0-2042-299.1.nflxso.net/dnm/api/v6...,https://images-na.ssl-images-amazon.com/images...,Argo,Heaven Without People,Lone Survivor,Wolf,Megan Leavey
2,Fair Game,Thriller,Arabic,Movie,PG-13,0.749848,https://www.netflix.com/watch/70119704,https://www.imdb.com/title/tt0977855,"Valerie Plame finds her life, career and marri...",https://occ-0-2042-299.1.nflxso.net/dnm/api/v6...,https://images-na.ssl-images-amazon.com/images...,Argo,Heaven Without People,Lone Survivor,Wolf,Megan Leavey
3,The Dark Knight Rises,Action,Arabic,Movie,PG-13,1.277717,https://www.netflix.com/watch/70213514,https://www.imdb.com/title/tt1345836,Billionaire Bruce Wayne must once again don th...,https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...,https://images-na.ssl-images-amazon.com/images...,Iron Man,Furious 7,John Wick: Chapter 3 - Parabellum,Taken,Hanna
4,The Dark Knight Rises,Adventure,Arabic,Movie,PG-13,1.277717,https://www.netflix.com/watch/70213514,https://www.imdb.com/title/tt1345836,Billionaire Bruce Wayne must once again don th...,https://occ-0-2851-38.1.nflxso.net/dnm/api/v6/...,https://images-na.ssl-images-amazon.com/images...,Iron Man,Furious 7,John Wick: Chapter 3 - Parabellum,Taken,Hanna

In [9]:
recs[recs['Title'] == 'Batman Begins'][['Title', 'Languages', 'Rec_1', 'Rec_2', 'Rec_3', 'Rec_4', 'Rec_5']]

,Title,Languages,Rec_1,Rec_2,Rec_3,Rec_4,Rec_5
6151,Batman Begins,English,The Dark Knight Rises,Star Trek,Spider-Man,Mission: Impossible 5,Batman v Superman: Dawn of Justice
6152,Batman Begins,English,The Dark Knight Rises,Star Trek,Spider-Man,Mission: Impossible 5,Batman v Superman: Dawn of Justice
23195,Batman Begins,Mandarin,The Dark Knight,Mission: Impossible III,Venom,The Forbidden Kingdom,Now You See Me 2
23196,Batman Begins,Mandarin,The Dark Knight,Mission: Impossible III,Venom,The Forbidden Kingdom,Now You See Me 2

In [13]:
recs[recs['Title'] == 'Criminal Minds'][['Title', 'Languages', 'Rec_1', 'Rec_2', 'Rec_3', 'Rec_4', 'Rec_5']]

,Title,Languages,Rec_1,Rec_2,Rec_3,Rec_4,Rec_5
29571,Criminal Minds,English,Sherlock,24,How to Get Away with Murder,Sons of Anarchy,NCIS
29572,Criminal Minds,English,Sherlock,24,How to Get Away with Murder,Sons of Anarchy,NCIS
29573,Criminal Minds,English,Sherlock,24,How to Get Away with Murder,Sons of Anarchy,NCIS
29574,Criminal Minds,English,Sherlock,24,How to Get Away with Murder,Sons of Anarchy,NCIS

In [19]:
recs[recs['Title'] == 'The Office (U.S.)'][['Title', 'Languages', 'Rec_1', 'Rec_2', 'Rec_3', 'Rec_4', 'Rec_5']]

,Title,Languages,Rec_1,Rec_2,Rec_3,Rec_4,Rec_5
29679,The Office (U.S.),English,Schitts Creek,Arrested Development,Parks and Recreation,Community,New Girl

In [20]:
movie = pd.read_csv('Movie_Data.csv')

movie.shape

(9425, 29)